### ISSUE TITLE
Create List of municipalities in the Area

### ISSUE THREAD

**Issue by khambrickKCDigital** [codeforkansascity/streetlights#12]

**Comment by JustVanessa** [comment]
[Streetlights_DataSources.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dc0201d554210014cf8c1b/125516c66e82c728ace21e0d46db8088268797a586eeb757b762d4953d47147c3c16a02e63c7af6aaf50740b0a0c0abe4b4a5a4daffc8e23a0be34788f0f0ab8d16d5e26cf3a40a5ea820da313f871d51bdaebe5c01982fa3737e683854e3b1e021d80fa5e37a19b4dc84abb.docx)
