### ISSUE TITLE
Create API For Mongo Back End Storage

### ISSUE THREAD

**Issue by mbostwick** [codeforkansascity/streetlights#29]
Create REST API for collecting data being posted, and ui requests

{	dataset:"X"
	possition:{
		lat:56.67
		long:-86.57
	},
	attributes{
		{
		name:""
		value:""
		},
		{
		name:""
		value:""
		}
	}
}

**Comment by noah-dev** [comment]
https://docs.google.com/document/d/1LkU_2XgPU-AYU9QgVwyWbLybyjfhppafptwl3veg2dw/edit

**Comment by mbostwick** [comment]
@AnwarJones please feel free to release WIP to the github. I need to make sure I true up the ETL conversion with the end points you have created.
