### ISSUE TITLE
Create Angular App For Visualizing GEO Data

### ISSUE THREAD

**Issue by mbostwick** [codeforkansascity/streetlights#30]
Create app for reading the api end point

**Comment by noah-dev** [comment]
•	Display data as a table/spreadsheet (including filtering options)
•	Display data on a map (including filtering options).

**Comment by mbostwick** [comment]
@jtanzi I noticed your fork, did you want to do a pull request ?

**Comment by jtanzi** [comment]
So far we have a basic app in place pulling mock data and displaying streetlight entries on a map.  Still need to add filtering and a spreadsheet view.

**Comment by jtanzi** [comment]
Closing issue, app created, will create new issues for app as individual tagged under angular-app.
