### ISSUE TITLE
Document TOS For Data Given To Use, and get sign off from data providers

### ISSUE THREAD

**Issue by mbostwick** [codeforkansascity/streetlights#33]
@khambrickKCDigital do we have any update on this ?

**Comment by khambrickKCDigital** [comment]
Working on creating this terms of service - getting into google doc for comments, will share when ready. Then I will be sharing it with Lees Summit first and asking them about their specific requirements @mbostwick

**Comment by khambrickKCDigital** [comment]
This is the disclaimer on the email from Lees Summit, which is the only requirement for hosting this data:

"This document is provided to the recipient pursuant to Section 610.011, RSMo, which requires public records to be made open to the public for inspection and copying.  It has not been prepared for use or reliance by any person or entity other than the City of Lee's Summit.  Information and data are supplied by various sources, and the City has made no independent investigation to determine the completeness and accuracy of information or data provided by persons or entities other than the City. The City makes no warranties and/or representations of any kind, express or implied, including without limitation any regarding merchantability or fitness for a particular purpose, regarding information, data, or service provided.  All information, data, and service are provided "as is," "with all faults," and by accepting receipt of this document, the recipient accepts the risk of any errors or omissions.  In no event shall the City be liable in any way to the users of information, data or service provided by the City.  Users of this information, data or service shall hold the City harmless in all matters and accounts arising from the use or reliance on the completeness or accuracy of this information, data or service. 
    If you would like to contribute to the accuracy of this document, please report any errors or omissions to City of Lee's Summit Information Technology Services. "
