### ISSUE TITLE
Translate problems in Meeting Notes to github issues

### ISSUE THREAD

**Issue by khambrickKCDigital** [codeforkansascity/streetlights#43]
Look at my notes and make suggestions on how to turn this into github issues. 
https://docs.google.com/document/u/1/d/1up2qAlWqerh6wMdxR6atjr-TY1bofh97gTkNJaevrV8/edit?usp=drive_web&ouid=109994111672460061546

**Comment by jtanzi** [comment]
I think this one is done, as I created a number of issues last week based on the meeting notes.  If someone wants to do a quick check that we haven't missed anything that should be here and close it out, please do.

**Comment by mbostwick** [comment]
I think it makes sense to close this. As part of getting travis running and mongo loaded with the data I'll likely do some clean up to make this project easier for contributors and for adding new things.
