### ISSUE TITLE
Make relevant search fields discrete (a dropdown)

### ISSUE THREAD

**Issue by MatthewScholefield** [codeforkansascity/streetlights#62]
The following columns have only a few possible values and should be compiled into a list of discrete values:
 - [ ] Wattage
 - [ ] Lumens
 - [ ] Attached Tech
 - [ ] Pole Owner
 - [ ] Data Source

This can be done from within the Angular front end code by creating a set of the values in each column.

**Comment by jtanzi** [comment]
I've pushed a commit that converts Wattage and Pole Owner to discrete dropdown filters in the table view, but I haven't yet seen any records that make use of lumens, and Data Source appears to be the same as Pole Owner. Attached Tech seems to either be a true or false value so a tri-state checkbox has been set up as a filter control.
