### ISSUE TITLE
To do with data

### ISSUE THREAD

**Issue by khambrickKCDigital** [codeforkansascity/streetlights#9]
Lee's Summit has Northing and Easting geolocation, which has caused problems. Now we are switching the KCMO geolocation to the Lee's Summit format to see if it has fewer errors.

**Comment by mbostwick** [comment]
@khambrickKCDigital I don't understand this issue. I'm working with getting the shape data and other entries into a readable format. Can We get a better description here ?

**Comment by mbostwick** [comment]
(unknown history)
